version: "3"


services: 
    api:
        container_name: thina-api-0.1
        command: "uvicorn app:app --reload --host 0.0.0.0 --port 8000"
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        env_file: .env
        
        restart: always